// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require("Witnet")
const WitnetRequestBoardProxy = artifacts.require("WitnetRequestBoardProxy")
const PriceFeed = artifacts.require("PriceFeed")

module.exports = async function (deployer) {
  await deployer.link(Witnet, [PriceFeed])
  await deployer.deploy(PriceFeed, WitnetRequestBoardProxy.address)
}
